# Deploy to server via SFTP with git-ftp and SSH key
name: Deploy via SFTP with git-ftp and SSH key

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for git-ftp

      - name: Set up SSH key and config
        env:
          SFTP_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SFTP_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.SFTP_HOST }} >> ~/.ssh/known_hosts
          
      - name: Install git-ftp
        run: |
          sudo apt-get update
          sudo apt-get install -y git-ftp

      - name: Configure git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Deploy via git-ftp using SSH key
        env:
          HOST: ${{ secrets.SFTP_HOST }}
          REMOTE_ROOT: ${{ secrets.SFTP_REMOTE_ROOT }}
          USERNAME: ${{ secrets.SFTP_USERNAME }}
        run: |
          git config git-ftp.url "sftp://$HOST"
          git config git-ftp.user "$USERNAME"
          git config git-ftp.key ~/.ssh/id_rsa
          git config git-ftp.insecure 1
          git ftp push --auto-init --remote-root "$REMOTE_ROOT" --verbose

      - name: Create environment file
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
            echo "# Google Maps API Configuration" > "$GITHUB_WORKSPACE/$REMOTE_ROOT/.env"
            echo "GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY" >> "$GITHUB_WORKSPACE/$REMOTE_ROOT/.env"
            echo "Environment file created with Google Maps API key in $REMOTE_ROOT"
